---
docker_package_map:
  'latest': docker-ce
  '18.06': docker-ce=18.06.3~ce~3-0~ubuntu
  '18.09': docker-ce=5:18.09.9~3-0~ubuntu-{{ ansible_distribution_release|lower }}
  '19.03': docker-ce=5:19.03.12~3-0~ubuntu-{{ ansible_distribution_release|lower }}
  'stable': docker-ce=5:18.09.9~3-0~ubuntu-{{ ansible_distribution_release|lower }}

docker_package: "{{ docker_package_map[docker_version | string] }}"
