---
dependencies:
  - role: container-engine/containerd
    when:
      - container_manager == 'containerd'
    tags:
      - container-engine
      - containerd

  - role: container-engine/docker
    when:
      - container_manager == 'docker'
    tags:
      - container-engine
      - docker
