---
- name: metrics-server | apply manifests
  block:

    - name: metrics-server | apply apiservice
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'apiservice.yml.j2') | from_yaml }}"
        kubeconfig: /etc/kubernetes/admin.conf

    - name: metrics-server | apply serviceaccount
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'serviceaccount.yml.j2') | from_yaml }}"
        kubeconfig: /etc/kubernetes/admin.conf

    - name: metrics-server | apply clusterrole
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'clusterrole.yml.j2') | from_yaml }}"
        kubeconfig: /etc/kubernetes/admin.conf

    - name: metrics-server | apply clusterrole-aggregated-reader
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'clusterrole-aggregated-reader.yml.j2') | from_yaml }}"
        kubeconfig: /etc/kubernetes/admin.conf

    - name: metrics-server | apply clusterrolebinding
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'clusterrolebinding.yml.j2') | from_yaml }}"
        kubeconfig: /etc/kubernetes/admin.conf

    - name: metrics-server | apply clusterrolebinding-auth-delegator
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'clusterrolebinding-auth-delegator.yml.j2') | from_yaml }}"
        kubeconfig: /etc/kubernetes/admin.conf

    - name: metrics-server | apply rolebinding
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'rolebinding.yml.j2') | from_yaml }}"
        kubeconfig: /etc/kubernetes/admin.conf

    - name: metrics-server | apply service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'service.yml.j2') | from_yaml }}"
        kubeconfig: /etc/kubernetes/admin.conf

    - name: metrics-server | apply deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'deployment.yml.j2') | from_yaml }}"
        kubeconfig: /etc/kubernetes/admin.conf

    - name: wait until metrics-server deployment is ready
      command: >-
        timeout -k 120s 120s kubectl --kubeconfig /etc/kubernetes/admin.conf
          rollout status Deployment/metrics-server -n {{ metrics_server_namespace }}
      changed_when: false

  when:
    - inventory_hostname in groups['k8s-master'][0]
