---
- name: kube-state-metrics | apply manifests
  block:

    - name: kube-state-metrics | apply serviceaccount
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'serviceaccount.yml.j2') | from_yaml }}"
        kubeconfig: /etc/kubernetes/admin.conf

    - name: kube-state-metrics | apply clusterrole
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'clusterrole.yml.j2') | from_yaml }}"
        kubeconfig: /etc/kubernetes/admin.conf

    - name: kube-state-metrics | apply clusterrolebinding
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'clusterrolebinding.yml.j2') | from_yaml }}"
        kubeconfig: /etc/kubernetes/admin.conf

    - name: kube-state-metrics | apply service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'service.yml.j2') | from_yaml }}"
        kubeconfig: /etc/kubernetes/admin.conf

    - name: kube-state-metrics | apply servicemonitor
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'servicemonitor.yml.j2') | from_yaml }}"
        kubeconfig: /etc/kubernetes/admin.conf

    - name: kube-state-metrics | apply deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'deployment.yml.j2') | from_yaml }}"
        kubeconfig: /etc/kubernetes/admin.conf

    - name: wait until kube-state-metrics deployment is ready
      command: >-
        timeout -k 120s 120s kubectl --kubeconfig /etc/kubernetes/admin.conf
          rollout status Deployment/kube-state-metrics -n {{ kube_state_metrics_namespace }}
      changed_when: false

  when:
    - inventory_hostname in groups['k8s-master'][0]
